[package]
name = "koan"
version = "0.1.0"
edition = "2021"

[lib]
name = "koan"
path = "src/lib.rs"

[[bin]]
name = "koan"
path = "src/main.rs"

[dependencies]
fxhash = "0.2.1"
rustyline = "14.0.0"

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"

