[package]
name = "koan"
version = "0.1.0"
edition = "2021"

[dependencies]
fxhash = "0.2.1"
rustyline = { version = "14.0.0", optional = true }

[features]
default = ["repl"]
repl = ["dep:rustyline"]

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"

