[package]
name = "koan"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyline = { version = "14.0.0", features = ["derive"] }
syntect = "5.2.0"

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"

